package entities;
// Generated 15 nov. 2015 13:36:36 by Hibernate Tools 4.3.1


import java.security.MessageDigest;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private String societe;
     private String telephone;
     private String email;
     private String addrLigne1;
     private String addrLigne2;
     private String ville;
     private String codePostal;
     private String motDePasse;
     private String salt;
     private Set videos = new HashSet(0);

    public Client() {
    }

	
    public Client(String societe, String telephone, String email, String codePostal, String motDePasse, String salt) {
        this.societe = societe;
        this.telephone = telephone;
        this.email = email;
        this.codePostal = codePostal;
        this.motDePasse = motDePasse;
        this.salt = salt;
    }
    public Client(String societe, String telephone, String email, String addrLigne1, String addrLigne2, String ville, String codePostal, String motDePasse, String salt, Set videos) {
       this.societe = societe;
       this.telephone = telephone;
       this.email = email;
       this.addrLigne1 = addrLigne1;
       this.addrLigne2 = addrLigne2;
       this.ville = ville;
       this.codePostal = codePostal;
       this.motDePasse = motDePasse;
       this.salt = salt;
       this.videos = videos;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public String getSociete() {
        return this.societe;
    }
    
    public void setSociete(String societe) {
        this.societe = societe;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddrLigne1() {
        return this.addrLigne1;
    }
    
    public void setAddrLigne1(String addrLigne1) {
        this.addrLigne1 = addrLigne1;
    }
    public String getAddrLigne2() {
        return this.addrLigne2;
    }
    
    public void setAddrLigne2(String addrLigne2) {
        this.addrLigne2 = addrLigne2;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }
    public String getMotDePasse() {
        return this.motDePasse;
    }
    
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public Set getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set videos) {
        this.videos = videos;
    }
    public static String sha256(String base) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(base.getBytes("UTF-8"));
            StringBuffer hexString = new StringBuffer();

            for (int i = 0; i < hash.length; i++) {
                String hex = Integer.toHexString(0xff & hash[i]);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }

            return hexString.toString();
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }


}


