package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private Integer idCompte;
     private String nom;
     private String prenom;
     private String login;
     private String password;
     private String salt;
     private Date creation;
     private int idTypeCompte;

    public Compte() {
    }

    public Compte(String nom, String prenom, String login, String password, String salt, Date creation, int idTypeCompte) {
       this.nom = nom;
       this.prenom = prenom;
       this.login = login;
       this.password = password;
       this.salt = salt;
       this.creation = creation;
       this.idTypeCompte = idTypeCompte;
    }
   
    public Integer getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(Integer idCompte) {
        this.idCompte = idCompte;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public int getIdTypeCompte() {
        return this.idTypeCompte;
    }
    
    public void setIdTypeCompte(int idTypeCompte) {
        this.idTypeCompte = idTypeCompte;
    }




}


