package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Diffusions generated by hbm2java
 */
public class Diffusions  implements java.io.Serializable {


     private Integer idDiffusion;
     private int idVideo;
     private int idMagasin;
     private int idTypeRayon;
     private Date dateDiffusion;

    public Diffusions() {
    }

    public Diffusions(int idVideo, int idMagasin, int idTypeRayon, Date dateDiffusion) {
       this.idVideo = idVideo;
       this.idMagasin = idMagasin;
       this.idTypeRayon = idTypeRayon;
       this.dateDiffusion = dateDiffusion;
    }
   
    public Integer getIdDiffusion() {
        return this.idDiffusion;
    }
    
    public void setIdDiffusion(Integer idDiffusion) {
        this.idDiffusion = idDiffusion;
    }
    public int getIdVideo() {
        return this.idVideo;
    }
    
    public void setIdVideo(int idVideo) {
        this.idVideo = idVideo;
    }
    public int getIdMagasin() {
        return this.idMagasin;
    }
    
    public void setIdMagasin(int idMagasin) {
        this.idMagasin = idMagasin;
    }
    public int getIdTypeRayon() {
        return this.idTypeRayon;
    }
    
    public void setIdTypeRayon(int idTypeRayon) {
        this.idTypeRayon = idTypeRayon;
    }
    public Date getDateDiffusion() {
        return this.dateDiffusion;
    }
    
    public void setDateDiffusion(Date dateDiffusion) {
        this.dateDiffusion = dateDiffusion;
    }




}


