package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * Diffusionstypesrayons generated by hbm2java
 */
public class Diffusionstypesrayons  implements java.io.Serializable {


     private DiffusionstypesrayonsId id;

    public Diffusionstypesrayons() {
    }

    public Diffusionstypesrayons(DiffusionstypesrayonsId id) {
       this.id = id;
    }
   
    public DiffusionstypesrayonsId getId() {
        return this.id;
    }
    
    public void setId(DiffusionstypesrayonsId id) {
        this.id = id;
    }




}


