package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * DiffusionstypesrayonsId generated by hbm2java
 */
public class DiffusionstypesrayonsId  implements java.io.Serializable {


     private int idVideo;
     private int idTypeRayon;

    public DiffusionstypesrayonsId() {
    }

    public DiffusionstypesrayonsId(int idVideo, int idTypeRayon) {
       this.idVideo = idVideo;
       this.idTypeRayon = idTypeRayon;
    }
   
    public int getIdVideo() {
        return this.idVideo;
    }
    
    public void setIdVideo(int idVideo) {
        this.idVideo = idVideo;
    }
    public int getIdTypeRayon() {
        return this.idTypeRayon;
    }
    
    public void setIdTypeRayon(int idTypeRayon) {
        this.idTypeRayon = idTypeRayon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DiffusionstypesrayonsId) ) return false;
		 DiffusionstypesrayonsId castOther = ( DiffusionstypesrayonsId ) other; 
         
		 return (this.getIdVideo()==castOther.getIdVideo())
 && (this.getIdTypeRayon()==castOther.getIdTypeRayon());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVideo();
         result = 37 * result + this.getIdTypeRayon();
         return result;
   }   


}


