package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * Diffusionregions generated by hbm2java
 */
public class Diffusionregions  implements java.io.Serializable {


     private DiffusionregionsId id;

    public Diffusionregions() {
    }

    public Diffusionregions(DiffusionregionsId id) {
       this.id = id;
    }
   
    public DiffusionregionsId getId() {
        return this.id;
    }
    
    public void setId(DiffusionregionsId id) {
        this.id = id;
    }




}


