package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * DiffusionregionsId generated by hbm2java
 */
public class DiffusionregionsId  implements java.io.Serializable {


     private int idVideo;
     private int idRegion;

    public DiffusionregionsId() {
    }

    public DiffusionregionsId(int idVideo, int idRegion) {
       this.idVideo = idVideo;
       this.idRegion = idRegion;
    }
   
    public int getIdVideo() {
        return this.idVideo;
    }
    
    public void setIdVideo(int idVideo) {
        this.idVideo = idVideo;
    }
    public int getIdRegion() {
        return this.idRegion;
    }
    
    public void setIdRegion(int idRegion) {
        this.idRegion = idRegion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DiffusionregionsId) ) return false;
		 DiffusionregionsId castOther = ( DiffusionregionsId ) other; 
         
		 return (this.getIdVideo()==castOther.getIdVideo())
 && (this.getIdRegion()==castOther.getIdRegion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVideo();
         result = 37 * result + this.getIdRegion();
         return result;
   }   


}


