package entities;



/**
 * Entreprise generated by hbm2java
 */
public class Entreprise  implements java.io.Serializable {


     private Integer idEntreprise;
     private String nom;
     private String adresse;
     private String code;
     private String ville;
     private String telephone;
     private String mail;

    public Entreprise() {
    }

	
    public Entreprise(String nom, String code, String telephone, String mail) {
        this.nom = nom;
        this.code = code;
        this.telephone = telephone;
        this.mail = mail;
    }
    public Entreprise(String nom, String adresse, String code, String ville, String telephone, String mail) {
       this.nom = nom;
       this.adresse = adresse;
       this.code = code;
       this.ville = ville;
       this.telephone = telephone;
       this.mail = mail;
    }
   
    public Integer getIdEntreprise() {
        return this.idEntreprise;
    }
    
    public void setIdEntreprise(Integer idEntreprise) {
        this.idEntreprise = idEntreprise;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }




}


