package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * Magasin generated by hbm2java
 */
public class Magasin  implements java.io.Serializable {


     private Integer idMagasin;
     private String nom;
     private String addrLigne1;
     private String addrLigne2;
     private String codePostal;
     private int idRegion;
     private String ville;

    public Magasin() {
    }

	
    public Magasin(String nom, String codePostal, int idRegion, String ville) {
        this.nom = nom;
        this.codePostal = codePostal;
        this.idRegion = idRegion;
        this.ville = ville;
    }
    public Magasin(String nom, String addrLigne1, String addrLigne2, String codePostal, int idRegion, String ville) {
       this.nom = nom;
       this.addrLigne1 = addrLigne1;
       this.addrLigne2 = addrLigne2;
       this.codePostal = codePostal;
       this.idRegion = idRegion;
       this.ville = ville;
    }
   
    public Integer getIdMagasin() {
        return this.idMagasin;
    }
    
    public void setIdMagasin(Integer idMagasin) {
        this.idMagasin = idMagasin;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAddrLigne1() {
        return this.addrLigne1;
    }
    
    public void setAddrLigne1(String addrLigne1) {
        this.addrLigne1 = addrLigne1;
    }
    public String getAddrLigne2() {
        return this.addrLigne2;
    }
    
    public void setAddrLigne2(String addrLigne2) {
        this.addrLigne2 = addrLigne2;
    }
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }
    public int getIdRegion() {
        return this.idRegion;
    }
    
    public void setIdRegion(int idRegion) {
        this.idRegion = idRegion;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }




}


