package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * Rayons generated by hbm2java
 */
public class Rayons  implements java.io.Serializable {


     private RayonsId id;

    public Rayons() {
    }

    public Rayons(RayonsId id) {
       this.id = id;
    }
   
    public RayonsId getId() {
        return this.id;
    }
    
    public void setId(RayonsId id) {
        this.id = id;
    }




}


