package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * RayonsId generated by hbm2java
 */
public class RayonsId  implements java.io.Serializable {


     private int idMagasin;
     private int idTypeRayon;

    public RayonsId() {
    }

    public RayonsId(int idMagasin, int idTypeRayon) {
       this.idMagasin = idMagasin;
       this.idTypeRayon = idTypeRayon;
    }
   
    public int getIdMagasin() {
        return this.idMagasin;
    }
    
    public void setIdMagasin(int idMagasin) {
        this.idMagasin = idMagasin;
    }
    public int getIdTypeRayon() {
        return this.idTypeRayon;
    }
    
    public void setIdTypeRayon(int idTypeRayon) {
        this.idTypeRayon = idTypeRayon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RayonsId) ) return false;
		 RayonsId castOther = ( RayonsId ) other; 
         
		 return (this.getIdMagasin()==castOther.getIdMagasin())
 && (this.getIdTypeRayon()==castOther.getIdTypeRayon());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMagasin();
         result = 37 * result + this.getIdTypeRayon();
         return result;
   }   


}


