package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private Integer idRegion;
     private String libelle;

    public Region() {
    }

    public Region(String libelle) {
       this.libelle = libelle;
    }
   
    public Integer getIdRegion() {
        return this.idRegion;
    }
    
    public void setIdRegion(Integer idRegion) {
        this.idRegion = idRegion;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


