package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * Typerayon generated by hbm2java
 */
public class Typerayon  implements java.io.Serializable {


     private Integer idTypeRayon;
     private String libelle;

    public Typerayon() {
    }

    public Typerayon(String libelle) {
       this.libelle = libelle;
    }
   
    public Integer getIdTypeRayon() {
        return this.idTypeRayon;
    }
    
    public void setIdTypeRayon(Integer idTypeRayon) {
        this.idTypeRayon = idTypeRayon;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


