package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1



/**
 * Typecompte generated by hbm2java
 */
public class Typecompte  implements java.io.Serializable {


     private Integer idTypeCompte;
     private String libelle;
     private String dblogin;
     private String dbpassword;

    public Typecompte() {
    }

    public Typecompte(String libelle, String dblogin, String dbpassword) {
       this.libelle = libelle;
       this.dblogin = dblogin;
       this.dbpassword = dbpassword;
    }
   
    public Integer getIdTypeCompte() {
        return this.idTypeCompte;
    }
    
    public void setIdTypeCompte(Integer idTypeCompte) {
        this.idTypeCompte = idTypeCompte;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public String getDblogin() {
        return this.dblogin;
    }
    
    public void setDblogin(String dblogin) {
        this.dblogin = dblogin;
    }
    public String getDbpassword() {
        return this.dbpassword;
    }
    
    public void setDbpassword(String dbpassword) {
        this.dbpassword = dbpassword;
    }




}


