package entities;
// Generated 12 nov. 2015 22:38:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Video generated by hbm2java
 */
public class Video  implements java.io.Serializable {


     private Integer idVideo;
     private String titre;
     private int frequence;
     private int duree;
     private Date dateDebut;
     private Date dateFin;
     private Date dateReception;
     private Date dateValidation;
     private double tarif;
     private int statut;
     private int idCommercial;
     private int idClient;

    public Video() {
    }

    public Video(String titre, int frequence, int duree, Date dateDebut, Date dateFin, Date dateReception, Date dateValidation, double tarif, int statut, int idCommercial, int idClient) {
       this.titre = titre;
       this.frequence = frequence;
       this.duree = duree;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.dateReception = dateReception;
       this.dateValidation = dateValidation;
       this.tarif = tarif;
       this.statut = statut;
       this.idCommercial = idCommercial;
       this.idClient = idClient;
    }
   
    public Integer getIdVideo() {
        return this.idVideo;
    }
    
    public void setIdVideo(Integer idVideo) {
        this.idVideo = idVideo;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public int getFrequence() {
        return this.frequence;
    }
    
    public void setFrequence(int frequence) {
        this.frequence = frequence;
    }
    public int getDuree() {
        return this.duree;
    }
    
    public void setDuree(int duree) {
        this.duree = duree;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public Date getDateReception() {
        return this.dateReception;
    }
    
    public void setDateReception(Date dateReception) {
        this.dateReception = dateReception;
    }
    public Date getDateValidation() {
        return this.dateValidation;
    }
    
    public void setDateValidation(Date dateValidation) {
        this.dateValidation = dateValidation;
    }
    public double getTarif() {
        return this.tarif;
    }
    
    public void setTarif(double tarif) {
        this.tarif = tarif;
    }
    public int getStatut() {
        return this.statut;
    }
    
    public void setStatut(int statut) {
        this.statut = statut;
    }
    public int getIdCommercial() {
        return this.idCommercial;
    }
    
    public void setIdCommercial(int idCommercial) {
        this.idCommercial = idCommercial;
    }
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }




}


